apiVersion: v1
kind: ConfigMap
metadata:
  name: dm-shop-config
  namespace: my-app
data:
  # This section defines the content of the file that will be mounted
  # The key 'app.env' will be the file name inside the container.
  app.env: |
    VITE_API_MODE=api
    VITE_BASE_API_URL=https://api.escuelajs.co/api/v1
    VITE_GEMINI_API_KEY=AIzaSyDKSltJJ4e2VjaFTwivwAJft_-Cd1lqkSg
