---
apiVersion: 'apps/v1'
kind: 'Deployment'
metadata:
  name: 'dm-shop-deployment'
  labels:
    app: 'dm-shop'
spec:
  replicas: 2
  selector:
    matchLabels:
      app: 'dm-shop'
  template:
    metadata:
      labels:
        app: 'dm-shop'
    spec:
      serviceAccountName: 'dm-shop-sa'
      containers:
      - name: 'dm-shop-container'
        image: 'johnnguyendeveloper/dm-shop:latest'
        imagePullPolicy: 'IfNotPresent'
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: 'config-volume'
          mountPath: '/app/config'
          subPath: 'app.env'
        readinessProbe:
          httpGet:
            path: '/'
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: '/'
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 10
      volumes:
      - name: 'config-volume'
        configMap:
          name: 'dm-shop-config'
          items:
          - key: 'app.env'
            path: 'app.env'
